<a href="https://colab.research.google.com/github/sindhura2770/tensors/blob/main/basic_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
x=tf.constant([[0,-2,-2],[0,1,2]])

In [ ]:
print(x)


tf.Tensor(
[[ 0 -2 -2]
 [ 0  1  2]], shape=(2, 3), dtype=int32)


In [ ]:
y=tf.fill([2,3],0)
print(y)


tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [ ]:
tf.math.equal(x,y)


<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True, False, False],
       [ True, False, False]])>

In [ ]:
tf.convert_to_tensor([1,5])


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>

In [ ]:
tf.convert_to_tensor(np.array([1,5]))

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 5])>

In [ ]:
tf.ones([]),tf.zeros([])


(<tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>)

In [ ]:
tf.zeros([])


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
tf.zeros([2,3])


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.ones([1,2])


<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [ ]:
tf.fill([2],6)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 6], dtype=int32)>

In [2]:
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1022999 ,  0.52053666],
       [-0.5972517 ,  0.29228392]], dtype=float32)>

In [4]:
tf.random.normal([2,2],mean=1,stddev=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.6676822 ,  3.9840713 ],
       [-0.15554631,  2.440246  ]], dtype=float32)>

In [5]:
tf.random.uniform([2,2],maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.8845031, 5.2341247],
       [3.4424794, 6.2388477]], dtype=float32)>

In [13]:
array=tf.constant([29.050888066,27.61298943, 31.19073486, 29.35532951 ,
0.97266006, 26.67541885, 38.08450317, 20.74983215,
4.94445419, 34.45999146 ,29.06485367, 36.01657104 ,
27.88236427, 20.56035233, 30.20379066, 29.51215172,
33.71149445, 28.59134293, 36.05556488, 28.66994858])
print(array)

tf.Tensor(
[29.050888   27.61299    31.190735   29.35533     0.97266006 26.675419
 38.084503   20.749832    4.944454   34.45999    29.064854   36.01657
 27.882364   20.560352   30.20379    29.512152   33.711494   28.591343
 36.055565   28.669949  ], shape=(20,), dtype=float32)


In [15]:
for idx,element in enumerate(array):
  if(element>30.0):
    tf.print(idx,element)

2 31.1907349
6 38.0845032
9 34.4599915
11 36.016571
14 30.2037907
16 33.7114944
18 36.0555649
