<a href="https://colab.research.google.com/github/sindhura2770/tensors/blob/main/operationsontensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
a=tf.constant([1,2,3,4])
b=tf.constant([10,21,35,46])

#Addition
x=tf.add(a,b)
print("Addition of a and b :",x)

Addition of a and b : tf.Tensor([11 23 38 50], shape=(4,), dtype=int32)


In [2]:
#subtraction
x=tf.subtract(a,b)
print("Subtraction of a and b:",x)

Subtraction of a and b: tf.Tensor([ -9 -19 -32 -42], shape=(4,), dtype=int32)


In [3]:
#multiplication
x=tf.multiply(a,b)
print("Multiplication of a and b:",x)

Multiplication of a and b: tf.Tensor([ 10  42 105 184], shape=(4,), dtype=int32)


In [5]:
#division
x=tf.divide(b,a)
print("Multiplication of a and b :",x)

Multiplication of a and b : tf.Tensor([10.         10.5        11.66666667 11.5       ], shape=(4,), dtype=float64)


In [16]:
x=tf.constant([3,3,3])
y=tf.constant([2,2,2])
div1=tf.divide(x,y)
print("div1:",div1)
div2=x/y
print("div2:",div2)
#div3=tf.div(x,y)
#print("div3",div3) # module 'tensorflow' has no attribute 'div'
div4=x//y
print("div4",div4)

div1: tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64)
div2: tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64)
div4 tf.Tensor([1 1 1], shape=(3,), dtype=int32)


In [20]:
p=tf.constant([1.0,2.0,3.5,4.6,5.5])
x=tf.math.log(p)
print("logarithm of p:",x)


logarithm of p: tf.Tensor([0.        0.6931472 1.2527629 1.5260563 1.704748 ], shape=(5,), dtype=float32)


In [21]:
x=tf.math.exp(p)
print(p)

tf.Tensor([1.  2.  3.5 4.6 5.5], shape=(5,), dtype=float32)
